### ISSUE TITLE
Dropbox Not Supported (Out of Box)

### ISSUE THREAD

**Issue by devotoare** [guilro/trellis-backup-role#18]
I had to enter the following commands to get Dropbox working:

1. Install pip: `apt install pip`
2. Upgrade pip (optional): `pip install --upgrade pip`
3. Install Dropbox module `pip install dropbox`

This was in additional to the additional setup steps which the documentation (both here and in duplicity) could not have made any less clear. Maybe there could be a flag for what the user is going to use that could install additional dependencies like this?

Full documentation for Dropbox:

### Create dropbox application
1. Go to https://www.dropbox.com/developers/apps/create 
2. Choose an API, type of access, and name the app (doesn't matter what you pick)

### vault.yml
Add target data to vault file:
```
vault_wordpress_sites:
  example.com:
    env:
      backup_target_user: <App key>
      backup_target_pass: <App secret>
```

### wordpress_sites.yml
Add backup info to wordpress_sites file:
```
wordpress_sites:
  example.com:
    env:
      backup:
        <insert other role variables from example in documentation>
        params:
        - 'export DPBX_ACCESS_TOKEN="<Generate Access Token from inside Dropbox App Settinngs>"'
```

**Edit:**
Without adding the pip commands you get `scheme not supported in url: dpbx:///`

**Comment by jillro** [comment]
Hello ! I will add an option in the following days to ansible-backup to automatically install optional dependencies specific to some blackends. In the meantime time, you can add it manually as a pre_tasks in your playbook.

**Comment by mockey** [comment]
Thanks for generally describing dropbox setup here.

A couple of remarks, which might be helpful for anyone else that needs this:
```yaml
backup_target_user: <App key>
backup_target_pass: <App secret>
```
in vault are not needed. If you add a `backup_target_user` you get a additional subdirectory in your dropbox app directory with that user name (ending with `@`). Probably it's added as a user to the URL like in scp and dropbox turns it into a subdirectory.
So only the `DPBX_ACCESS_TOKEN` is actually needed and probably should go into the vault.

If you want your backups directly in your dropbox app folder you need to set `target` to `dbpx://` with 2 slashes instead of 3, otherwise a 4th slash is added. also `backup` section should not be under `env` in `wordpress_sites.yml`.

So my config looks like this:

**vault.yml**
```yaml
vault_dpbx_access_token: "<generated access token>" #simply in the root
...
```

**wordpress_sites.yml**
```yaml
wordpress_sites:
  example.com:
    ...
    backup:
      ...
      target: dpbx://
      params:
        - 'export DPBX_ACCESS_TOKEN="{{ vault_dpbx_access_token }}"'
```

I also added a `install.yml` for adding pip and the dropbox module:
**install.yml**
```yaml
---

- name: Install pip
  apt:
    name: python-pip

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install dropbox module
  pip:
    name: dropbox
```
I simply added that file to `trellis-backup/tasks` and included it in `main.yml`. This should probably go into `lafranceinsoumise.backup` somewhere, depending on the dpbx target...
