### ISSUE TITLE
"'item' is undefined" when trying to provision

### ISSUE THREAD

**Issue by raphaelsuzuki** [guilro/trellis-backup-role#30]
I'm using the latest version of this role and tried both with B2 and S3 targets, only to find this error when provisioning:

```
TASK [lafranceinsoumise.backup : backup-configure | Ensure backup directories exist] *********
System info:
  Ansible 2.7.10; Linux
  Trellis 1.0.3: April 30th, 2019
---------------------------------------------------
'item' is undefined
fatal: [000.my.ip.000]: FAILED! => {}
```

Here's the last version I tried of my 'wordpress_sites.yml' file:

```
    cache:
      enabled: false
    backup:
      enabled: true
      auto: true
      target: s3://my.bucket.url/
      schedule: '30 17 * * *'
      purge: false
      max_age: 1M
      full_max_age: 1M
      params:
       - 'export S3_USE_SIGV4="True"'
```

**Comment by Xilonz** [comment]
Thank you for reporting.

Are you sure production/wordpress_sites.yml contains the content you're showing above? Not accidentally placed in another env/wordpress_sites.yml? 

Can you run the ansible-playbook with `-vvv` for verbose output and show us the relevant part?

You will only get `'item' is undefined` when there's no site in `wordpress_sites.yml` defined with `backup`. We should add a check and throw a warning if this is the case.

**Comment by raphaelsuzuki** [comment]
Hi @Xilonz 

Thanks for your prompt response.

I ran Ansible again with -vvv and it only gave me one more line regarding the failure:

```
task path: /var/www/mysite.com/trellis/vendor/roles/lafranceinsoumise.backup/tasks/configure.yml:10
```

I double checked the file `wordpress_sites.yml` and it comes indeed from the production environment. Actually I have some changes from another role right above `backups` that could only have come from production, as you can see below in the full contents of said file, only with sensitive information redacted:

```
# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  mysite.com:
    site_hosts:
      - canonical: mysite.com
        redirects:
          - www.mysite.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@my.git.repo:raphaelsuzuki/mysite.com.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      stapling_enabled: false
      provider: cloudflare-origin-ca
    cache:
      enabled: false
    backup:
      enabled: true
      auto: true
      target: s3://my.bucket.url/
      schedule: '30 17 * * *'
      purge: false
      max_age: 1M
      full_max_age: 1M
      params:
       - 'export S3_USE_SIGV4="True"'
```
