### ISSUE TITLE
Invalid data passed to 'loop', it requires a list

### ISSUE THREAD

**Issue by Twansparant** [guilro/trellis-backup-role#42]
Hi there,

We've been using your excellent backup role for all of our production servers and it works great!
In my latest project using these versions:

1. Ansible 2.13.3 (system 2.10.17)
1. Trellis 1.16.0
1. backup 2.1.7
1. lafranceinsoumise.backup 5.5.0

I am suddenly getting an ansible error while re-provisioning:

```
TASK [lafranceinsoumise.backup : Install backup profile dependencies] **********
System info:
  Ansible 2.13.3; Darwin
  Trellis 1.16.0: July 18th, 2022
---------------------------------------------------
Invalid data passed to 'loop', it requires a list, got this instead:
[{'name': 'example.com_uploads', 'schedule': '0 4 * * *', 'source':
'/srv/www/example.com/shared/uploads', 'target':
's3://ams3.digitaloceanspaces.com/backups/example.com//uploads',
'target_user': False, 'target_pass': False, 'max_age': '3M', 'full_max_age':
'1M', 'max_full_backups': '3', 'params': ['export S3_USE_SIGV4="True"'],
'action': 'purge_backup --force'}] + [{'name': 'example.com_database',
'schedule': '0 4 * * *', 'source': 'mysql://example.com_production', 'target':
's3://ams3.digitaloceanspaces.com/backups/example.com//database',
'target_user': False, 'target_pass': False, 'max_age': '3M', 'full_max_age':
'1M', 'max_full_backups': '3', 'params': ['export S3_USE_SIGV4="True"'],
'action': 'purge_backup --force'}]. Hint: If you passed a list/dict of just
one element, try adding wantlist=True to your lookup invocation or use
q/query instead of lookup.
fatal: [159.223.217.50]: FAILED! => {}
```

I'm using the exact same variables as in my other projects which provisioned without any errors?
In my `wordpress_sites.yml`:

```yaml
    backup:
      enabled: true
      auto: true
      target: s3://ams3.digitaloceanspaces.com/backups/example.com/
      schedule: '0 4 * * *'
      purge: true
      max_age: 3M
      full_max_age: 1M
      max_full_backups: 3
      params:
        - 'export S3_USE_SIGV4="True"'
```

In my `vault.yml`:

```yaml
backup_env:
  AWS_ACCESS_KEY_ID: XXXXXXXX
  AWS_SECRET_ACCESS_KEY: XXXXXXXX
```

I can see the `{{ backup_profiles }}` variable being constructed [here](https://github.com/Xilonz/trellis-backup-role/blob/master/tasks/main.yml#L45) as:
```yaml
[{...}] + [{...}]
```
But the error states this is not a valid ansible list syntax?
I'm guessing this has to do with my project's ansible version since the other projects run fine?

Anyone else bumped into this?
Thanks!
