### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by simonpeters** [guilro/trellis-backup-role#7]
Hello,

Is there a way to debug and see if the backups are working?

I set it up for google cloud storage, but it doesn't seem to backup, and can't seem to find any cronjobs running.

**Comment by jillro** [comment]
You can check there is a `backup` file in `/etc/crond.d`.

Then, you can check you backup profile by running them manually :
`duply /etc/duply/example.com_uploads backup`
`duply /etc/duply/example.com_database backup`

**Comment by robyurkowski** [comment]
To add: you should also inspect the logs in `/var/www/duply/`.

**Comment by amankapoor** [comment]
> You can check there is a `backup` file in `/etc/crond.d`.
> 
> Then, you can check you backup profile by running them manually :
> `duply /etc/duply/example.com_uploads backup`
> `duply /etc/duply/example.com_database backup`

Hey @guilro, what I love about duply is the way we configure all the settings, but unfortunately, I am unable to get it working.

I checked the ```backup``` file inside ```/etc/cron.d``` and the output is as following. Looks all good to me.
```
# This file was generated by Ansible for domain-staging.c.google-cloud-project-name.internal
# Do NOT modify this file by hand!

# Run backups
*/5 * * * * root /usr/bin/duply /etc/duply/sub.domain.com_uploads backup >> /var/log/duply/sub.domain.com_uploads.log 2>&1
*/5 * * * * root /usr/bin/duply /etc/duply/sub.domain.com_database backup >> /var/log/duply/sub.domain.com_database.log 2>&1
```

Then I tried to manually run the backup using the command that you have given ```duply /etc/duply/example.com_uploads backup``` and this time output is something that needs attention.

```
Start duply v2.0.3, time is 2019-03-12 16:47:40.

Sorry. A fatal ERROR occured:

Profile folder in '/etc/duply/sub.domain.com_uploads' cannot be accessed.

Hint: 
 Check the filesystem permissions and set directory accessible e.g. 'chmod 700'.
```

(PS: Another thing to note here is that, it shows v2.0.3 got installed, but my ```requirements.yml``` mention v2.1.4)

As the errors says to check filesystem permissions, this is what I get when I run ```stat sub.domain.com_uploads/```

```
  File: sub.domain.com_uploads/
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d      Inode: 520840      Links: 2
Access: (0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-03-12 16:05:01.425982176 +0000
Modify: 2019-03-12 16:03:37.674535759 +0000
Change: 2019-03-12 16:03:37.674535759 +0000
 Birth: -
```

I tried to ```cd``` into ```/etc/duply/sub.domain.com_uploads/``` but it says ```bash: cd: sub.domain.com_uploads/: Permission denied```

Could you please help me understand what am I missing?

Also, I am using Google Cloud Storage, and I think I should share how I set it up.

I manually created a bucket with the name ```sub.domain.com``` and followed the instructions in readme. The target is ```target: gs://sub.domain.com```. Then I activated the interoperatibility and this is how my vault looks

```
vault_wordpress_sites:
  sub.domain.com:
    env:
      db_password: "2g%U@OwocnB2QRH^rfrX0%YtV&Wp9h"
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "Z7oTGE|,]=lC:#B!ftD{k`KQY,U#axvKwSFHZfWTc>,C9yIS:d{=J^&]g%84]cdP"
      secure_auth_key: "B*wvK{)0uvx-8ofqzSpc?U!J/p%.JCcLVi/wT/!%6*uKS)RJ4#x5sqlG@0%&u,F="
      logged_in_key: "t<M9.-k[vRO]CmBQtMN$hE9cpZB0Azyrcb343]0+-)>!EJTro!=Uq2mqrzB%G:yZ"
      nonce_key: "g!c2d_VA-`&hKIvUY/sMQ4!OpiuFSZ/*y6D4;dIv52r3lKo4U=>aQOSXuOo/HhOX"
      auth_salt: "jTR@@4^87$J8f+vm#;x&9?jV2x>0ImSaE},4iD31=?xun[vk*rj#?-#P%Q{+otsA"
      secure_auth_salt: "?$5M.:#rYZV*+_/+*8LSUR6IS;OI2f=ss|O}Dr@9$4jBA37$;f_<&P{`8_!H2<f<"
      logged_in_salt: "uT`)$pi>en(z4U/2m#mBuRzie/3xL?v{l.*LsTpv.m%#C(z69w:jPK]I<ppQ5#*="
      nonce_salt: "BHiOyNpv`7M1$MOUJ}agMD-[=qV{B`Gb^EQQ=4EdA-s:9ie+_.:Yl(vo{:,0M#+]"
      # Backup env
      backup_target_user: GOOGYKN2FC........ (ACCESS KEY HERE)
      backup_target_pass: QIUZ0aEm7JIC.........(SECRET HERE)
```

And this is how my ```wordpress_sites.yml``` looks

```
wordpress_sites:
  sub.domain.com:
    .
    .
    backup:
      enabled: true
      auto: true # CHANGE TO FALSE LATER
      target: gs://sub.domain.com # any location supported by duplicity
      schedule: "*/5 * * * *" # cron time of backups (change this value)
      purge: false # switch to true to enable automatic purging of old backups
      max_age: 1M # time frame for old backups to keep, Used for the "purge" command.
      full_max_age: 1M # forces a full backup if last full backup reaches this age.
```
Please help.

Also, @robyurkowski, there is only ```html``` directory inside my ```/var/www/```, so couldn't see any logs.

And @simonpeters, could you please also take a look at my problem and may be help me please? You might have it working by now.

Also @guilro, if you approve, then I would like to enhance the documentation by having a description somewhere which would essentially say how to get it working with Google Cloud.

Looking forward to hear from you.

Thanks.
